<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ViewProfile Positivecase</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0d9933d7-7c4c-4193-88ee-7719d6ca5ecd</testSuiteGuid>
   <testCaseLink>
      <guid>f1d62050-8d8e-437e-bd57-10b1600d11c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MAIN/WebSupport/ViewProfile byMSISN</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37fdceca-f014-4191-b0d8-40d1c8d529e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0d62c03-6af5-4816-9bb4-e615f65dd1fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a5bd9d4-0ca9-4247-bdb6-e261b2f7aaa4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d397849-aeb0-4149-858c-2e64f6d5f86e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MAIN/WebSupport/ViewProfile byNIK</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd2d8dc3-a0e6-4002-b186-3f95b87f9438</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cea6138-8ebb-44f0-b99b-89dc54650396</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25318e53-b145-45c6-b80c-941ac8c70d91</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
